services:
  mc:
    container_name: mc-server-homelab
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575" 
    environment:
      EULA: "TRUE"
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ./data:/data
